//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_MyJs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int user_id { get; set; }
        public int heritage_id { get; set; }
        public System.DateTime create_time { get; set; }
        public string detail { get; set; }
        public int UserId { get; set; }
        public int HeritageId { get; set; }
        public int AdminId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Heritage Heritage { get; set; }
        public virtual Admin Admin { get; set; }
    }
}
